#!/usr/bin/env bash
#=========================================================================
# 05-sta-signoff
#=========================================================================
# Static Timing Analysis and Sign-off: runs the static timing analysis
# and sign-off process on the post-synthesis netlist from 02-synth.

# Stop on error and echo all commands

set -e
trap 'echo "CMD: $BASH_COMMAND"' DEBUG

# Colors

RED="\e[31m"
GREEN="\e[32m"
RESET="\e[0m"

# Determine RUNDIR

RUNDIR="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))"
cd $RUNDIR